# Site settings
title:      wikihive
email:        
author:      
description: "wikihive - Lets re-invent education together"
baseurl:     
url: "http://wikihive.org"

permalink: /blog/:title
 
# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: 
twitter_username: wikihive14
facebook_id: wikihive
google_plus_id: 
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
